import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import boundaries from 'eslint-plugin-boundaries'
import importPlugin from 'eslint-plugin-import'
import { defineConfig, globalIgnores } from 'eslint/config'

// Layer table from ADR-0002. Update tsconfig.app.json + vite.config.ts paths in
// lockstep when adding a layer; ESLint resolves @-aliases via the tsconfig.
const layers = ['core', 'ports', 'adapters', 'services', 'plugins', 'app', 'ui']

// Layers now live in three places: core + ports are workspace packages (#93);
// the plugin layers are workspace packages too (#94/#95, see pluginPackages);
// and the host layers (adapters/services/app/ui) live in the apps/ide app
// package (#96). The @-aliases are unchanged — only the on-disk base dir differs.
const layerDir = (name) =>
  name === 'core' || name === 'ports'
    ? `packages/${name}/src`
    : `apps/ide/src/${name}`

// Plugins carved into their own workspace packages (#94 onward). Still the
// 'plugins' layer — same import rules — just relocated under packages/. Add a
// package dir here as each plugin moves out of src/plugins/.
const pluginPackages = [
  'toolchain-mads', 'toolchain-ca65', 'toolchain-z88dk',
  'machine-atari-xl', 'machine-c64', 'machine-nes', 'machine-zx',
  'emulator-c64-chips', 'emulator-nes-jsnes', 'emulator-zx-chips',
  'debug-atari-6502', 'debug-zx-z80',
  'panel-memory', 'panel-output', 'panel-ppu', 'panel-registers',
  'converters', 'editors',
]

// Two patterns per layer so EVERY file is classified, not just sub-folders:
//  - folder mode catches `<base>/<subdir>/…` (storage-idb/, emu/, …)
//  - file mode catches files sitting DIRECTLY under the layer dir
//    (e.g. src/adapters/plugin-loader.ts). Without the file rule those root
//    files are unclassified and imports of them dodge the boundary check (#25).
const elementTypes = [
  ...layers.flatMap((name) => [
    { type: name, pattern: `${layerDir(name)}/*`, mode: 'folder' },
    { type: name, pattern: `${layerDir(name)}/*.{ts,tsx}`, mode: 'file' },
  ]),
  ...pluginPackages.flatMap((pkg) => [
    { type: 'plugins', pattern: `packages/${pkg}/src/*`, mode: 'folder' },
    { type: 'plugins', pattern: `packages/${pkg}/src/*.{ts,tsx}`, mode: 'file' },
  ]),
]

// allow[X] = which layers X may import. Mirror of ADR-0002's table.
// Same-layer imports are always permitted; added explicitly per row.
const allowed = {
  core: ['core'],
  ports: ['core', 'ports'],
  adapters: ['core', 'ports', 'adapters'],
  services: ['core', 'ports', 'services'],
  plugins: ['core', 'ports', 'plugins'],
  app: ['core', 'ports', 'services', 'plugins', 'adapters', 'app'],
  ui: ['core', 'ports', 'services', 'app', 'ui'],
}

// boundaries/dependencies rule shape (v6 object selectors):
//   { from: { type }, allow: { to: { type: [...allowed] } } }
const dependencyRules = layers.map((from) => ({
  from: { type: from },
  allow: { to: { type: allowed[from] } },
}))

export default defineConfig([
  globalIgnores([
    'dist',
    'node_modules',
    '_notes',
    'public',
    '.direnv',
    '.emcache',
    'apps/docs/.astro', // generated by `astro sync` — not ours to lint
    'apps/docs/dist', // Astro build output — generated, not ours to lint
    'apps/ide/dist', // Vite build output — generated, not ours to lint
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
    },
    plugins: { boundaries, import: importPlugin },
    settings: {
      'boundaries/elements': elementTypes,
      'boundaries/include': ['apps/ide/src/**/*', 'packages/**/*'],
      'import/resolver': {
        typescript: { project: './apps/ide/tsconfig.app.json' },
      },
    },
    rules: {
      'boundaries/dependencies': [
        'error',
        { default: 'disallow', rules: dependencyRules },
      ],

      // React-hooks v7 React-Compiler-readiness rules, now enforced (#28): the
      // app adopted React Compiler (vite.config.ts) and was restructured to
      // satisfy them — latest-ref writes moved into effects, derived state moved
      // to adjust-during-render, the label scan cache moved to module scope. A
      // few genuine resource/error-path effects keep inline disables.
      'react-hooks/set-state-in-effect': 'error',
      'react-hooks/refs': 'error',
      'react-hooks/preserve-manual-memoization': 'error',
      // exhaustive-deps stays enforced — it catches real stale-closure bugs.
      'react-hooks/exhaustive-deps': 'warn',
      'preserve-caught-error': 'off',

      // Guardrail: stray console.log/debug/group in app code is a code smell —
      // logging goes through the Logger port (@adapters/logger). console.warn /
      // console.error stay allowed for genuine fallback/crash paths. The
      // dev-only event logger keeps inline disables for its console.group calls.
      'no-console': ['error', { allow: ['warn', 'error'] }],

      // Module barrel discipline: cross-folder imports use a folder's barrel.
      // Forbid only deep alias paths (depth >= 2); leave relative imports
      // (`./sibling`, `./sub/file`) alone — those are intra-folder concerns.
      // External deps (react, vitest, …) are also untouched.
      'import/no-internal-modules': [
        'error',
        {
          forbid: [
            '@core/*/*',
            '@ports/*/*',
            '@adapters/*/*',
            '@services/*/*',
            '@app/*/*',
            '@ui/*/*',
            // Plugins are workspace packages now — forbid deep imports past the
            // package entry (only the package's exports map should be reachable).
            '@madside/*/*',
          ],
        },
      ],
      // main.tsx + Vite entry sit at src/ root — not a layer. Exempt from
      // boundaries; they're allowed to import from @ui.
    },
  },
  {
    files: ['apps/ide/src/main.tsx'],
    rules: { 'boundaries/dependencies': 'off' },
  },
  {
    // Radix wrapper modules deliberately re-export primitive parts alongside
    // the wrapper component (one import site for the whole primitive). Fast
    // Refresh granularity doesn't apply — turn the rule off for these wrappers.
    files: ['apps/ide/src/ui/components/ui/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
])
