export * from './createWorkbench'
// Only the pure diff helper is public — the `storage` singleton stays internal
// (imported solely by workbench-context, the composition root) so the data layer
// can't reach for the global instead of the injected `workbench.storage` (#16).
export { diffSnapshots } from './storage'
export * from './export-project'
export * from './fileTemplates'
export * from './templates'
export * from './courses'
export * from './course-project'
export * from './course-author'
export * from './plugin-trust'
export * from './course-fetch'
export * from './official-courses'
export * from './check-runner'
export * from './labels'
export * from './cSysroot'
export * from './theme'
export * from './github-config'
export * from './github-repos'
export * from './github-sync'
export * from './github-context'
export * from './workbench-context'
export * from './plugin-registry-glue'
export * as state from './state'
